export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';

export const FETCH_BUILDS = 'FETCH_BUILDS';
export const FETCH_BUILDS_SUCCESS = 'FETCH_BUILDS_SUCCESS';

export const SET_TFS_URL = 'SET_TFS_URL';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
